# LunaChat v2.0.2
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

noJoinAsGlobal: true
loggingChat: true
globalMarker: '!'
zeroMemberRemove: false
showListOnJoin: false
createChannelOnJoinCommand: true
globalChannel: ''
ngword: []
ngwordAction: mask

japanizeType: kana
japanizeDisplayLine: 2
japanizeLine1Format: '%msg (%japanize)'
japanizeLine2Format: '&6[JP] %japanize'
